// Define the syntax version for Protocol Buffers

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: practice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SomeEnum_Value int32

const (
	SomeEnum_A SomeEnum_Value = 0
	SomeEnum_B SomeEnum_Value = 1
	SomeEnum_C SomeEnum_Value = 3
)

// Enum value maps for SomeEnum_Value.
var (
	SomeEnum_Value_name = map[int32]string{
		0: "A",
		1: "B",
		3: "C",
	}
	SomeEnum_Value_value = map[string]int32{
		"A": 0,
		"B": 1,
		"C": 3,
	}
)

func (x SomeEnum_Value) Enum() *SomeEnum_Value {
	p := new(SomeEnum_Value)
	*p = x
	return p
}

func (x SomeEnum_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SomeEnum_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_practice_proto_enumTypes[0].Descriptor()
}

func (SomeEnum_Value) Type() protoreflect.EnumType {
	return &file_practice_proto_enumTypes[0]
}

func (x SomeEnum_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SomeEnum_Value.Descriptor instead.
func (SomeEnum_Value) EnumDescriptor() ([]byte, []int) {
	return file_practice_proto_rawDescGZIP(), []int{0, 0}
}

// Enum representing some values
type SomeEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SomeEnum) Reset() {
	*x = SomeEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SomeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeEnum) ProtoMessage() {}

func (x *SomeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_practice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeEnum.ProtoReflect.Descriptor instead.
func (*SomeEnum) Descriptor() ([]byte, []int) {
	return file_practice_proto_rawDescGZIP(), []int{0}
}

// Message representing nested fields
type ToNest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewField int64     `protobuf:"varint,1,opt,name=newField,proto3" json:"newField,omitempty"`
	CoolEnum *SomeEnum `protobuf:"bytes,2,opt,name=coolEnum,proto3" json:"coolEnum,omitempty"`
}

func (x *ToNest) Reset() {
	*x = ToNest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToNest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToNest) ProtoMessage() {}

func (x *ToNest) ProtoReflect() protoreflect.Message {
	mi := &file_practice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToNest.ProtoReflect.Descriptor instead.
func (*ToNest) Descriptor() ([]byte, []int) {
	return file_practice_proto_rawDescGZIP(), []int{1}
}

func (x *ToNest) GetNewField() int64 {
	if x != nil {
		return x.NewField
	}
	return 0
}

func (x *ToNest) GetCoolEnum() *SomeEnum {
	if x != nil {
		return x.CoolEnum
	}
	return nil
}

// Message representing the request
type AReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	G        bool      `protobuf:"varint,1,opt,name=G,proto3" json:"G,omitempty"`
	K        *ToNest   `protobuf:"bytes,2,opt,name=K,proto3" json:"K,omitempty"`
	AlsoEnum *SomeEnum `protobuf:"bytes,3,opt,name=alsoEnum,proto3" json:"alsoEnum,omitempty"`
}

func (x *AReq) Reset() {
	*x = AReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AReq) ProtoMessage() {}

func (x *AReq) ProtoReflect() protoreflect.Message {
	mi := &file_practice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AReq.ProtoReflect.Descriptor instead.
func (*AReq) Descriptor() ([]byte, []int) {
	return file_practice_proto_rawDescGZIP(), []int{2}
}

func (x *AReq) GetG() bool {
	if x != nil {
		return x.G
	}
	return false
}

func (x *AReq) GetK() *ToNest {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *AReq) GetAlsoEnum() *SomeEnum {
	if x != nil {
		return x.AlsoEnum
	}
	return nil
}

// Message representing the response
type BResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R bool `protobuf:"varint,1,opt,name=R,proto3" json:"R,omitempty"`
}

func (x *BResp) Reset() {
	*x = BResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BResp) ProtoMessage() {}

func (x *BResp) ProtoReflect() protoreflect.Message {
	mi := &file_practice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BResp.ProtoReflect.Descriptor instead.
func (*BResp) Descriptor() ([]byte, []int) {
	return file_practice_proto_rawDescGZIP(), []int{3}
}

func (x *BResp) GetR() bool {
	if x != nil {
		return x.R
	}
	return false
}

var File_practice_proto protoreflect.FileDescriptor

var file_practice_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x70, 0x61, 0x6b, 0x22, 0x28, 0x0a, 0x08, 0x53, 0x6f, 0x6d, 0x65, 0x45, 0x6e, 0x75,
	0x6d, 0x22, 0x1c, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x05, 0x0a, 0x01, 0x41, 0x10,
	0x00, 0x12, 0x05, 0x0a, 0x01, 0x42, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01, 0x43, 0x10, 0x03, 0x22,
	0x4f, 0x0a, 0x06, 0x54, 0x6f, 0x4e, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6e, 0x65, 0x77,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x29, 0x0a, 0x08, 0x63, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x61, 0x6b, 0x2e, 0x53, 0x6f,
	0x6d, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x08, 0x63, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x75, 0x6d,
	0x22, 0x5a, 0x0a, 0x04, 0x41, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x47, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x01, 0x47, 0x12, 0x19, 0x0a, 0x01, 0x4b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x61, 0x6b, 0x2e, 0x54, 0x6f, 0x4e, 0x65, 0x73, 0x74, 0x52, 0x01,
	0x4b, 0x12, 0x29, 0x0a, 0x08, 0x61, 0x6c, 0x73, 0x6f, 0x45, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x61, 0x6b, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x45, 0x6e,
	0x75, 0x6d, 0x52, 0x08, 0x61, 0x6c, 0x73, 0x6f, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x15, 0x0a, 0x05,
	0x42, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x52, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x01, 0x52, 0x32, 0x2d, 0x0a, 0x09, 0x4d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x20, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x09, 0x2e, 0x70, 0x61,
	0x6b, 0x2e, 0x41, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x70, 0x61, 0x6b, 0x2e, 0x42, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_practice_proto_rawDescOnce sync.Once
	file_practice_proto_rawDescData = file_practice_proto_rawDesc
)

func file_practice_proto_rawDescGZIP() []byte {
	file_practice_proto_rawDescOnce.Do(func() {
		file_practice_proto_rawDescData = protoimpl.X.CompressGZIP(file_practice_proto_rawDescData)
	})
	return file_practice_proto_rawDescData
}

var file_practice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_practice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_practice_proto_goTypes = []interface{}{
	(SomeEnum_Value)(0), // 0: pak.SomeEnum.Value
	(*SomeEnum)(nil),    // 1: pak.SomeEnum
	(*ToNest)(nil),      // 2: pak.ToNest
	(*AReq)(nil),        // 3: pak.AReq
	(*BResp)(nil),       // 4: pak.BResp
}
var file_practice_proto_depIdxs = []int32{
	1, // 0: pak.ToNest.coolEnum:type_name -> pak.SomeEnum
	2, // 1: pak.AReq.K:type_name -> pak.ToNest
	1, // 2: pak.AReq.alsoEnum:type_name -> pak.SomeEnum
	3, // 3: pak.MyService.Message:input_type -> pak.AReq
	4, // 4: pak.MyService.Message:output_type -> pak.BResp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_practice_proto_init() }
func file_practice_proto_init() {
	if File_practice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_practice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SomeEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToNest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_practice_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_practice_proto_goTypes,
		DependencyIndexes: file_practice_proto_depIdxs,
		EnumInfos:         file_practice_proto_enumTypes,
		MessageInfos:      file_practice_proto_msgTypes,
	}.Build()
	File_practice_proto = out.File
	file_practice_proto_rawDesc = nil
	file_practice_proto_goTypes = nil
	file_practice_proto_depIdxs = nil
}
